

DEFAULT_HTTP_HANDLER = None

HTTP_GET = 'GET'
HTTP_HEAD = 'HEAD'

HTTP_PUT = 'PUT'
HTTP_POST = 'POST'
HTTP_DELETE = 'DELETE'
HTTP_OPTIONS = 'OPTIONS'
HTTP_TRACE = 'TRACE'
HTTP_CONNECT = 'CONNECT'

HTTP_METHODS = HTTP_GET, HTTP_PUT, HTTP_DELETE, HTTP_POST, HTTP_HEAD, HTTP_OPTIONS, HTTP_TRACE

# Separators for parsing a URI string.
SCHEME_SEPARATOR = ":"
AUTHORITY_SEPARATOR = "//"
DEVICE_IDENTIFIER = ":"
SEGMENT_SEPARATOR = "/"
QUERY_SEPARATOR = "?"
FRAGMENT_SEPARATOR = "#"
USER_INFO_SEPARATOR = "@"
PORT_SEPARATOR = ":"

def uri(uri):
    from web.urilib import URI
    return URI(uri, DEFAULT_HTTP_HANDLER)
